import { suggestTemplate } from "@/lib/catalog";
import type { Listing, Order, ShopState } from "@/lib/types";

const PRINT_FILE =
  "https://cdn-origin.gelato-api-dashboard.ie.live.gelato.tech/docs/sample-print-files/logo.png";

function listing(
  partial: Omit<Listing, "issues" | "gelatoUnitCost"> & {
    gelatoUnitCost?: number;
    mapped?: boolean;
  },
): Listing {
  const template = partial.gelatoProductUid
    ? suggestTemplate(partial.title, partial.tags)
    : undefined;
  const mapped = Boolean(partial.gelatoProductUid && partial.printFileUrl);
  const issues: string[] = [];
  if (partial.state === "expired") issues.push("Listing expired on Etsy");
  if (partial.state === "active" && !partial.gelatoProductUid) {
    issues.push("Not mapped to a Gelato product");
  }
  if (partial.state === "active" && !partial.printFileUrl) {
    issues.push("Missing print file");
  }
  return {
    ...partial,
    gelatoUnitCost: partial.gelatoUnitCost ?? template?.unitCost ?? 8.4,
    issues,
    gelatoProductName: mapped
      ? partial.gelatoProductName
      : partial.gelatoProductName,
  };
}

const listings: Listing[] = [
  listing({
    id: "lst_sage",
    etsyListingId: "1849203311",
    title: "Sage Line Botanical Print · 12×16",
    state: "active",
    price: 28,
    currency: "USD",
    quantity: 999,
    views: 1842,
    favorites: 216,
    tags: ["botanical", "poster", "sage", "line art"],
    category: "poster",
    gelatoProductUid: "posters_pt_poster_ps_12x16-in_pt_200-gsm-coated_cl_4-0_ver",
    gelatoProductName: "Poster 12×16 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 8.4,
  }),
  listing({
    id: "lst_horizon",
    etsyListingId: "1849204412",
    title: "Coastal Horizon Canvas · 16×20",
    state: "active",
    price: 68,
    currency: "USD",
    quantity: 999,
    views: 963,
    favorites: 141,
    tags: ["canvas", "coastal", "horizon"],
    category: "canvas",
    gelatoProductUid: "wall_art_canvas_ps_16x20-in_pt_canvas_cl_4-0",
    gelatoProductName: "Canvas 16×20 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 22.1,
  }),
  listing({
    id: "lst_mug",
    etsyListingId: "1849205513",
    title: "Midnight Garden Mug",
    state: "active",
    price: 22,
    currency: "USD",
    quantity: 999,
    views: 2214,
    favorites: 308,
    tags: ["mug", "garden", "ceramic"],
    category: "mug",
    gelatoProductUid: "mugs_11oz_white_wrap",
    gelatoProductName: "Ceramic mug 11 oz",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 7.8,
  }),
  listing({
    id: "lst_tee",
    etsyListingId: "1849206614",
    title: "Olive Grove Unisex Tee",
    state: "active",
    price: 32,
    currency: "USD",
    quantity: 40,
    views: 1288,
    favorites: 174,
    tags: ["tee", "olive", "apparel"],
    category: "apparel",
    gelatoProductUid:
      "apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_m_gco_natural_gpr_4-4",
    gelatoProductName: "Unisex tee · natural · M",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 12.4,
  }),
  listing({
    id: "lst_rain",
    etsyListingId: "1849207715",
    title: "Rain Window Print · 12×16",
    state: "active",
    price: 26,
    currency: "USD",
    quantity: 999,
    views: 412,
    favorites: 38,
    tags: ["poster", "rain", "window"],
    category: "poster",
  }),
  listing({
    id: "lst_card",
    etsyListingId: "1849208816",
    title: "Sunday Market Greeting Card",
    state: "active",
    price: 8,
    currency: "USD",
    quantity: 999,
    views: 640,
    favorites: 91,
    tags: ["card", "market", "stationery"],
    category: "card",
    gelatoProductUid: "cards_pf_a5_pt_350-gsm-coated-silk_cl_4-4_ver",
    gelatoProductName: "Greeting card A5",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 2.4,
  }),
  listing({
    id: "lst_pine",
    etsyListingId: "1849209917",
    title: "Winter Pine Study · 18×24",
    state: "expired",
    price: 36,
    currency: "USD",
    quantity: 0,
    views: 3011,
    favorites: 402,
    tags: ["poster", "pine", "winter"],
    category: "poster",
    gelatoProductUid: "posters_pt_poster_ps_18x24-in_pt_200-gsm-coated_cl_4-0_ver",
    gelatoProductName: "Poster 18×24 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 12.9,
  }),
  listing({
    id: "lst_thin",
    etsyListingId: "1849210018",
    title: "Mini Fern Postcard Print",
    state: "active",
    price: 9,
    currency: "USD",
    quantity: 999,
    views: 188,
    favorites: 12,
    tags: ["poster", "fern", "mini"],
    category: "poster",
    gelatoProductUid: "posters_pt_poster_ps_12x16-in_pt_200-gsm-coated_cl_4-0_ver",
    gelatoProductName: "Poster 12×16 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 8.4,
  }),
];

const orders: Order[] = [
  {
    id: "ord_1042",
    etsyReceiptId: "3218901042",
    buyerName: "Maya Chen",
    createdAt: "2026-09-12T16:40:00.000Z",
    paidAt: "2026-09-12T16:41:12.000Z",
    status: "paid",
    subtotal: 28,
    shippingPaid: 4.5,
    currency: "USD",
    items: [
      {
        id: "txn_1042a",
        listingId: "lst_sage",
        title: "Sage Line Botanical Print · 12×16",
        quantity: 1,
        price: 28,
        gelatoProductUid:
          "posters_pt_poster_ps_12x16-in_pt_200-gsm-coated_cl_4-0_ver",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Maya",
      lastName: "Chen",
      addressLine1: "418 Valencia St",
      city: "San Francisco",
      state: "CA",
      postCode: "94103",
      country: "US",
      email: "maya.chen@example.com",
    },
    trackingPushedToEtsy: false,
    issues: [],
  },
  {
    id: "ord_1041",
    etsyReceiptId: "3218901041",
    buyerName: "Owen Blake",
    createdAt: "2026-09-12T09:12:00.000Z",
    paidAt: "2026-09-12T09:13:40.000Z",
    status: "blocked",
    subtotal: 26,
    shippingPaid: 4.5,
    currency: "USD",
    items: [
      {
        id: "txn_1041a",
        listingId: "lst_rain",
        title: "Rain Window Print · 12×16",
        quantity: 1,
        price: 26,
      },
    ],
    shippingAddress: {
      firstName: "Owen",
      lastName: "Blake",
      addressLine1: "77 Dean St",
      city: "London",
      postCode: "W1D 3SZ",
      country: "GB",
      email: "owen.blake@example.com",
    },
    trackingPushedToEtsy: false,
    issues: ["Line item is not mapped to Gelato"],
  },
  {
    id: "ord_1038",
    etsyReceiptId: "3218901038",
    buyerName: "Priya Raman",
    createdAt: "2026-09-11T18:05:00.000Z",
    paidAt: "2026-09-11T18:06:22.000Z",
    status: "in_production",
    subtotal: 90,
    shippingPaid: 0,
    currency: "USD",
    items: [
      {
        id: "txn_1038a",
        listingId: "lst_horizon",
        title: "Coastal Horizon Canvas · 16×20",
        quantity: 1,
        price: 68,
        gelatoProductUid: "wall_art_canvas_ps_16x20-in_pt_canvas_cl_4-0",
        printFileUrl: PRINT_FILE,
      },
      {
        id: "txn_1038b",
        listingId: "lst_mug",
        title: "Midnight Garden Mug",
        quantity: 1,
        price: 22,
        gelatoProductUid: "mugs_11oz_white_wrap",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Priya",
      lastName: "Raman",
      addressLine1: "19 Willow Ave",
      city: "Austin",
      state: "TX",
      postCode: "78704",
      country: "US",
      email: "priya.raman@example.com",
    },
    gelatoOrderId: "GEL-883421",
    gelatoStatus: "printing",
    trackingPushedToEtsy: false,
    issues: [],
  },
  {
    id: "ord_1033",
    etsyReceiptId: "3218901033",
    buyerName: "Jonah Wells",
    createdAt: "2026-09-09T14:22:00.000Z",
    paidAt: "2026-09-09T14:22:48.000Z",
    status: "shipped",
    subtotal: 32,
    shippingPaid: 5.5,
    currency: "USD",
    items: [
      {
        id: "txn_1033a",
        listingId: "lst_tee",
        title: "Olive Grove Unisex Tee",
        quantity: 1,
        price: 32,
        variation: "M / Natural",
        gelatoProductUid:
          "apparel_product_gca_t-shirt_gsc_crewneck_gcu_unisex_gqa_classic_gsi_m_gco_natural_gpr_4-4",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Jonah",
      lastName: "Wells",
      addressLine1: "5407 N Mississippi Ave",
      city: "Portland",
      state: "OR",
      postCode: "97217",
      country: "US",
      email: "jonah.wells@example.com",
    },
    gelatoOrderId: "GEL-882901",
    gelatoStatus: "shipped",
    trackingNumber: "9400111899562537861247",
    trackingCarrier: "USPS",
    trackingPushedToEtsy: false,
    issues: ["Tracking is on Gelato but not on the Etsy receipt"],
  },
  {
    id: "ord_1024",
    etsyReceiptId: "3218901024",
    buyerName: "Elena Voss",
    createdAt: "2026-09-04T11:08:00.000Z",
    paidAt: "2026-09-04T11:08:19.000Z",
    status: "delivered",
    subtotal: 56,
    shippingPaid: 4.5,
    currency: "USD",
    items: [
      {
        id: "txn_1024a",
        listingId: "lst_sage",
        title: "Sage Line Botanical Print · 12×16",
        quantity: 2,
        price: 28,
        gelatoProductUid:
          "posters_pt_poster_ps_12x16-in_pt_200-gsm-coated_cl_4-0_ver",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Elena",
      lastName: "Voss",
      addressLine1: "8 Rue des Archives",
      city: "Paris",
      postCode: "75004",
      country: "FR",
      email: "elena.voss@example.com",
    },
    gelatoOrderId: "GEL-880114",
    gelatoStatus: "delivered",
    trackingNumber: "3SGELO88114421",
    trackingCarrier: "DHL",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1018",
    etsyReceiptId: "3218901018",
    buyerName: "Chris Adeyemi",
    createdAt: "2026-08-28T20:41:00.000Z",
    paidAt: "2026-08-28T20:41:33.000Z",
    status: "delivered",
    subtotal: 22,
    shippingPaid: 5.1,
    currency: "USD",
    items: [
      {
        id: "txn_1018a",
        listingId: "lst_mug",
        title: "Midnight Garden Mug",
        quantity: 1,
        price: 22,
        gelatoProductUid: "mugs_11oz_white_wrap",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Chris",
      lastName: "Adeyemi",
      addressLine1: "210 Atlantic Ave",
      city: "Brooklyn",
      state: "NY",
      postCode: "11201",
      country: "US",
      email: "chris.adeyemi@example.com",
    },
    gelatoOrderId: "GEL-878220",
    gelatoStatus: "delivered",
    trackingNumber: "927489012334561",
    trackingCarrier: "UPS",
    trackingPushedToEtsy: true,
    issues: [],
  },
];

export const DEMO_SHOP: ShopState = {
  shopName: "Hearth & Line",
  currency: "USD",
  listings,
  orders,
  lastSyncAt: "2026-09-13T01:10:00.000Z",
};

export function seedShop(): ShopState {
  return structuredClone(DEMO_SHOP);
}
