import { PRINT_FILE, HARVEST_DROP_ID } from "@/lib/constants";
import type { Listing, Order, ShopState } from "@/lib/types";

export const HARVEST_LISTINGS: Listing[] = [
  {
    id: "lst_hoodie",
    etsyListingId: "1849211101",
    title: "River Reed Pullover Hoodie",
    state: "active",
    price: 73.99,
    currency: "USD",
    quantity: 999,
    views: 640,
    favorites: 88,
    tags: ["hoodie", "reed", "apparel", "botanical"],
    category: "hoodie",
    gelatoProductUid:
      "apparel_product_gca_hoodie_gsc_pullover_gcu_unisex_gqa_classic_gsi_m_gco_sand_gpr_4-0",
    gelatoProductName: "Unisex pullover hoodie · sand · M",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 28.4,
    drop: HARVEST_DROP_ID,
    issues: [],
  },
  {
    id: "lst_tote",
    etsyListingId: "1849211102",
    title: "Market Day Canvas Tote",
    state: "active",
    price: 29.99,
    currency: "USD",
    quantity: 999,
    views: 1512,
    favorites: 247,
    tags: ["tote", "bag", "market", "canvas"],
    category: "tote",
    gelatoProductUid:
      "bags_product_gca_tote-bag_gsc_canvas_gcu_unisex_gsi_os_gco_natural_gpr_4-0",
    gelatoProductName: "Canvas tote · natural · one size",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 9.2,
    drop: HARVEST_DROP_ID,
    issues: [],
  },
  {
    id: "lst_frame",
    etsyListingId: "1849211103",
    title: "Amber Field Oak Framed Print",
    state: "active",
    price: 69.99,
    currency: "USD",
    quantity: 999,
    views: 804,
    favorites: 132,
    tags: ["framed", "oak", "field", "wall art"],
    category: "framed",
    gelatoProductUid: "framed-posters_pt_poster_ps_12x16-in_frame_oak_pt_200-gsm_cl_4-0_ver",
    gelatoProductName: "Oak framed print 12×16 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 24.8,
    drop: HARVEST_DROP_ID,
    issues: [],
  },
  {
    id: "lst_calendar",
    etsyListingId: "1849211104",
    title: "Hearth Year Wall Calendar 2027",
    state: "active",
    price: 43.99,
    currency: "USD",
    quantity: 999,
    views: 1188,
    favorites: 196,
    tags: ["calendar", "2027", "wall", "planner"],
    category: "calendar",
    gelatoProductUid: "calendars_wall_ps_11x17-in_pt_200-gsm_cl_4-4_ver",
    gelatoProductName: "Wall calendar 11×17 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 15.2,
    drop: HARVEST_DROP_ID,
    issues: [],
  },
  {
    id: "lst_pillow",
    etsyListingId: "1849211105",
    title: "Linen Path Throw Pillow",
    state: "active",
    price: 46.99,
    currency: "USD",
    quantity: 999,
    views: 733,
    favorites: 109,
    tags: ["pillow", "linen", "home", "cushion"],
    category: "pillow",
    gelatoProductUid: "home_cushion_ps_18x18-in_pt_poly_cl_4-0",
    gelatoProductName: "Throw pillow 18×18 in",
    printFileUrl: PRINT_FILE,
    gelatoUnitCost: 16.4,
    drop: HARVEST_DROP_ID,
    issues: [],
  },
];

export const HARVEST_ORDERS: Order[] = [
  {
    id: "ord_1108",
    etsyReceiptId: "3218901108",
    buyerName: "Lena Ortiz",
    createdAt: "2026-09-12T19:18:00.000Z",
    paidAt: "2026-09-12T19:18:41.000Z",
    status: "delivered",
    subtotal: 103.98,
    shippingPaid: 0,
    currency: "USD",
    items: [
      {
        id: "txn_1108a",
        listingId: "lst_hoodie",
        title: "River Reed Pullover Hoodie",
        quantity: 1,
        price: 73.99,
        variation: "M / Sand",
        gelatoProductUid:
          "apparel_product_gca_hoodie_gsc_pullover_gcu_unisex_gqa_classic_gsi_m_gco_sand_gpr_4-0",
        printFileUrl: PRINT_FILE,
      },
      {
        id: "txn_1108b",
        listingId: "lst_tote",
        title: "Market Day Canvas Tote",
        quantity: 1,
        price: 29.99,
        gelatoProductUid:
          "bags_product_gca_tote-bag_gsc_canvas_gcu_unisex_gsi_os_gco_natural_gpr_4-0",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Lena",
      lastName: "Ortiz",
      addressLine1: "902 W 12th St",
      city: "Austin",
      state: "TX",
      postCode: "78703",
      country: "US",
      email: "lena.ortiz@example.com",
    },
    gelatoOrderId: "GEL-890108",
    gelatoStatus: "delivered",
    trackingNumber: "9400111899562890108",
    trackingCarrier: "USPS",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1106",
    etsyReceiptId: "3218901106",
    buyerName: "Harper Diaz",
    createdAt: "2026-09-11T13:04:00.000Z",
    paidAt: "2026-09-11T13:04:22.000Z",
    status: "shipped",
    subtotal: 87.98,
    shippingPaid: 5.5,
    currency: "USD",
    items: [
      {
        id: "txn_1106a",
        listingId: "lst_calendar",
        title: "Hearth Year Wall Calendar 2027",
        quantity: 2,
        price: 43.99,
        gelatoProductUid: "calendars_wall_ps_11x17-in_pt_200-gsm_cl_4-4_ver",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Harper",
      lastName: "Diaz",
      addressLine1: "44 Pineapple St",
      city: "Brooklyn",
      state: "NY",
      postCode: "11201",
      country: "US",
      email: "harper.diaz@example.com",
    },
    gelatoOrderId: "GEL-890106",
    gelatoStatus: "shipped",
    trackingNumber: "1Z999AA10123456784",
    trackingCarrier: "UPS",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1104",
    etsyReceiptId: "3218901104",
    buyerName: "Noah Kim",
    createdAt: "2026-09-10T16:51:00.000Z",
    paidAt: "2026-09-10T16:51:19.000Z",
    status: "in_production",
    subtotal: 69.99,
    shippingPaid: 0,
    currency: "USD",
    items: [
      {
        id: "txn_1104a",
        listingId: "lst_frame",
        title: "Amber Field Oak Framed Print",
        quantity: 1,
        price: 69.99,
        gelatoProductUid: "framed-posters_pt_poster_ps_12x16-in_frame_oak_pt_200-gsm_cl_4-0_ver",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Noah",
      lastName: "Kim",
      addressLine1: "2101 N 4th Ave",
      city: "Seattle",
      state: "WA",
      postCode: "98109",
      country: "US",
      email: "noah.kim@example.com",
    },
    gelatoOrderId: "GEL-890104",
    gelatoStatus: "printing",
    trackingPushedToEtsy: false,
    issues: [],
  },
  {
    id: "ord_1101",
    etsyReceiptId: "3218901101",
    buyerName: "Amira Sol",
    createdAt: "2026-09-08T11:22:00.000Z",
    paidAt: "2026-09-08T11:22:44.000Z",
    status: "delivered",
    subtotal: 76.98,
    shippingPaid: 0,
    currency: "USD",
    items: [
      {
        id: "txn_1101a",
        listingId: "lst_pillow",
        title: "Linen Path Throw Pillow",
        quantity: 1,
        price: 46.99,
        gelatoProductUid: "home_cushion_ps_18x18-in_pt_poly_cl_4-0",
        printFileUrl: PRINT_FILE,
      },
      {
        id: "txn_1101b",
        listingId: "lst_tote",
        title: "Market Day Canvas Tote",
        quantity: 1,
        price: 29.99,
        gelatoProductUid:
          "bags_product_gca_tote-bag_gsc_canvas_gcu_unisex_gsi_os_gco_natural_gpr_4-0",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Amira",
      lastName: "Sol",
      addressLine1: "15 Rue de Charonne",
      city: "Paris",
      postCode: "75011",
      country: "FR",
      email: "amira.sol@example.com",
    },
    gelatoOrderId: "GEL-890101",
    gelatoStatus: "delivered",
    trackingNumber: "3SGELO89010122",
    trackingCarrier: "DHL",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1096",
    etsyReceiptId: "3218901096",
    buyerName: "Theo Park",
    createdAt: "2026-09-06T09:40:00.000Z",
    paidAt: "2026-09-06T09:40:18.000Z",
    status: "delivered",
    subtotal: 73.99,
    shippingPaid: 6.8,
    currency: "USD",
    items: [
      {
        id: "txn_1096a",
        listingId: "lst_hoodie",
        title: "River Reed Pullover Hoodie",
        quantity: 1,
        price: 73.99,
        variation: "M / Sand",
        gelatoProductUid:
          "apparel_product_gca_hoodie_gsc_pullover_gcu_unisex_gqa_classic_gsi_m_gco_sand_gpr_4-0",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Theo",
      lastName: "Park",
      addressLine1: "88 Queen St W",
      city: "Toronto",
      postCode: "M5H 0A1",
      country: "CA",
      email: "theo.park@example.com",
    },
    gelatoOrderId: "GEL-890096",
    gelatoStatus: "delivered",
    trackingNumber: "9400111899562890096",
    trackingCarrier: "USPS",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1092",
    etsyReceiptId: "3218901092",
    buyerName: "Sofia Berg",
    createdAt: "2026-09-03T18:15:00.000Z",
    paidAt: "2026-09-03T18:15:31.000Z",
    status: "delivered",
    subtotal: 113.98,
    shippingPaid: 0,
    currency: "USD",
    items: [
      {
        id: "txn_1092a",
        listingId: "lst_frame",
        title: "Amber Field Oak Framed Print",
        quantity: 1,
        price: 69.99,
        gelatoProductUid: "framed-posters_pt_poster_ps_12x16-in_frame_oak_pt_200-gsm_cl_4-0_ver",
        printFileUrl: PRINT_FILE,
      },
      {
        id: "txn_1092b",
        listingId: "lst_calendar",
        title: "Hearth Year Wall Calendar 2027",
        quantity: 1,
        price: 43.99,
        gelatoProductUid: "calendars_wall_ps_11x17-in_pt_200-gsm_cl_4-4_ver",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Sofia",
      lastName: "Berg",
      addressLine1: "12 Södermalmvägen",
      city: "Stockholm",
      postCode: "118 46",
      country: "SE",
      email: "sofia.berg@example.com",
    },
    gelatoOrderId: "GEL-890092",
    gelatoStatus: "delivered",
    trackingNumber: "SEPOST890092331",
    trackingCarrier: "PostNord",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1088",
    etsyReceiptId: "3218901088",
    buyerName: "Sam Okonkwo",
    createdAt: "2026-09-01T15:02:00.000Z",
    paidAt: "2026-09-01T15:02:11.000Z",
    status: "delivered",
    subtotal: 59.98,
    shippingPaid: 4.9,
    currency: "USD",
    items: [
      {
        id: "txn_1088a",
        listingId: "lst_tote",
        title: "Market Day Canvas Tote",
        quantity: 2,
        price: 29.99,
        gelatoProductUid:
          "bags_product_gca_tote-bag_gsc_canvas_gcu_unisex_gsi_os_gco_natural_gpr_4-0",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Sam",
      lastName: "Okonkwo",
      addressLine1: "401 Mass Ave",
      city: "Cambridge",
      state: "MA",
      postCode: "02139",
      country: "US",
      email: "sam.okonkwo@example.com",
    },
    gelatoOrderId: "GEL-890088",
    gelatoStatus: "delivered",
    trackingNumber: "9400111899562890088",
    trackingCarrier: "USPS",
    trackingPushedToEtsy: true,
    issues: [],
  },
  {
    id: "ord_1084",
    etsyReceiptId: "3218901084",
    buyerName: "Jun Ito",
    createdAt: "2026-08-30T21:11:00.000Z",
    paidAt: "2026-08-30T21:11:27.000Z",
    status: "delivered",
    subtotal: 46.99,
    shippingPaid: 6.1,
    currency: "USD",
    items: [
      {
        id: "txn_1084a",
        listingId: "lst_pillow",
        title: "Linen Path Throw Pillow",
        quantity: 1,
        price: 46.99,
        gelatoProductUid: "home_cushion_ps_18x18-in_pt_poly_cl_4-0",
        printFileUrl: PRINT_FILE,
      },
    ],
    shippingAddress: {
      firstName: "Jun",
      lastName: "Ito",
      addressLine1: "2-14-1 Jingumae",
      city: "Tokyo",
      postCode: "150-0001",
      country: "JP",
      email: "jun.ito@example.com",
    },
    gelatoOrderId: "GEL-890084",
    gelatoStatus: "delivered",
    trackingNumber: "JP890084221556",
    trackingCarrier: "Japan Post",
    trackingPushedToEtsy: true,
    issues: [],
  },
];

export function applyHarvestDrop(shop: ShopState) {
  let changed = false;
  for (const listing of HARVEST_LISTINGS) {
    if (!shop.listings.some((row) => row.id === listing.id)) {
      shop.listings.push(structuredClone(listing));
      changed = true;
    }
  }
  for (const order of HARVEST_ORDERS) {
    if (!shop.orders.some((row) => row.id === order.id)) {
      shop.orders.push(structuredClone(order));
      changed = true;
    }
  }
  return changed;
}
